#!/usr/bin/env python3
"""Share identical generated 8/10/12pt CJK indices without changing glyph data."""

import argparse
from pathlib import Path
import re


SHARED_NAME = "notosans_cjk_commonIntervals"
SHARED_FILE = "notosans_cjk_common_intervals.h"


def shared_outputs(directory):
    headers = []
    tables = []
    for size in (8, 10, 12):
        name = f"notosans_cjk_{size}"
        path = directory / f"{name}.h"
        text = path.read_text()
        pattern = rf"static const EpdUnicodeInterval {name}Intervals\[\] = \{{(.*?)\n\}};\n"
        match = re.search(pattern, text, re.S)
        if match:
            body = match[1]
            text = text[:match.start()] + text[match.end():]
            text = text.replace(f"{name}Intervals,", f"{SHARED_NAME},")
            text = text.replace('#include "EpdFontData.h"',
                                f'#include "EpdFontData.h"\n#include "{SHARED_FILE}"')
        elif f'#include "{SHARED_FILE}"' in text and f"{SHARED_NAME}," in text:
            shared = (directory / SHARED_FILE).read_text()
            body = re.search(rf"{SHARED_NAME}\[\] = \{{(.*?)\n\}};", shared, re.S).group(1)
        else:
            raise ValueError(f"{path}: missing interval table")
        table = [tuple(int(value, 16) for value in row)
                 for row in re.findall(r"\{\s*(0x[\dA-F]+),\s*(0x[\dA-F]+),\s*(0x[\dA-F]+)\s*\}", body)]
        if not table or (tables and table != tables[0]):
            raise ValueError(f"{path}: CJK interval tables differ; refusing to share")
        tables.append(table)
        headers.append((path, text))

    shared = ('// Generated by share-cn-font-intervals.py; do not edit.\n'
              '#pragma once\n#include "EpdFontData.h"\n\n'
              f'inline constexpr EpdUnicodeInterval {SHARED_NAME}[] = {{\n')
    shared += ''.join(f'    {{ 0x{first:X}, 0x{last:X}, 0x{offset:X} }},\n'
                      for first, last, offset in tables[0])
    shared += '};\n'
    return [(directory / SHARED_FILE, shared), *headers]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", nargs="?", type=Path,
                        default=Path(__file__).resolve().parent.parent / "builtinFonts")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    # Validate every table before replacing any output.
    outputs = shared_outputs(args.directory)
    for path, content in outputs:
        if path.exists() and path.read_text() == content:
            continue
        if args.check:
            raise SystemExit(f"{path}: shared CJK indices need regeneration")
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(content)
        temporary.replace(path)


if __name__ == "__main__":
    main()
