apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - workload.yaml
configMapGenerator:
  - name: crossmux-ota-code
    files:
      - mirror_ota_release.py
      - serve_ota_release.py
      - hook_ota_release.py
